# Generated by Django 5.1.4 on 2025-01-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Gain Muscle', 'Gain Muscle'), ('Maintain', 'Maintain')], default='Maintain', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='training_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
