# Generated by Django 5.1.4 on 2025-01-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_goal_userprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
