# Generated by Django 5.1.4 on 2025-01-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdetails_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='goal',
            field=models.CharField(choices=[('lose-weight', 'Lose Weight'), ('gain-muscle', 'Gain Muscle'), ('maintain', 'Maintain Weight')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Gain Muscle', 'Gain Muscle'), ('Maintain', 'Maintain Weight')], default='Maintain', max_length=50),
        ),
    ]
