# Generated by Django 5.1.5 on 2025-01-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
